# CI de N 01 - Disparo manual a partir de 1 clique, tem que cuidar bem os espaçapamentos

# nome do nosso 'pepeline'
name: 'n1'

# regras de Disparo (gatilhos/triggers)
# gatinho de exec manual = workflow_dispatch

on:
  workflow_dispatch:

# trabalhos/tarefas dentro do pepeline = jobs
jobs:
  run-mocha-tests:    

    # maquina que o job vai executar
    runs-on: ubuntu-latest

    # passos do script de build
    steps:
       # clone do projeto
      - name: Checkout do Código
        uses: actions/checkout@v4

      # instalacao do node
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x # Recomendo usar uma versão LTS estável como 20.x ou 22.x

      # instalacao do Yarn (o Yarn é um pacote global que o npm pode instalar)
      - name: Instalando Yarn CLI
        run: npm install -g yarn

      # instalacao das dependencias do projeto (incluindo o Mocha)
      - name: Instalando Dependências do Projeto
        run: yarn install --frozen-lockfile # 'yarn' é o mesmo que 'yarn install'

      # --- REMOVIDO: Instalacao do Playwright (pois os testes são Mocha) ---
      # - name: Instalando Playwright
      #   run: yarn playwright install

      # executar os testes Mocha
      - name: Executando Testes com Mocha
        run: yarn run test # ALTERADO: Aponta para o script 'test' que executa o Mocha