# CI de Nivel 02 - Disparo agendado

# nome do nosso 'pepeline'
name: 'Execução Agendada'

# regras de Disparo (gatilhos/triggers)
# gatinho de exec manual = workflow_dispatch

on:
  schedule:
    - cron: '50 21 16 * 3'

# trabalhos/tarefas dentro do pepeline = jobs
jobs:
  e2e-tests:    

    # maquina que o job vai executar
    runs-on: ubuntu-latest

    # passos do script de build
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalacao do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # instalacao do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalacao das dependencias
      - name: Instalando dependencias
        run: yarn

      # instalacao do Playwright
      - name: Instalando Playwright
        run: yarn playwright install

      # executar os testes e2e
      - name:  Executando testes E2E
        run: yarn run e2e